Add locations
aurre/UNO-Cuban-Style pull request #1
Opened 2018-11-24 18:40 UTC by aurre

2018-11-24 23:19 UTC, Latinneo commented on public/index.html
> +    <link rel="icon" href="<%= BASE_URL %>favicon.png" />
Busca como convertir la imagen a .ico, es el formato standard para favorite icons.

2018-11-24 23:22 UTC, arieldellano commented on src/store/modules/game/index.js
> +const BASE_URL = 'http://localhost:3000/';
Mueve esto a un file externo. Podrias ponerlo en una carpeta src/config/app-settings.json o algo asi y luego importarlo aqui, de esa manera no tienes que repetirlo en los componentes si hay que cambiarlo, se cambia en un solo lugar.

2018-11-24 23:23 UTC, arieldellano commented on src/store/modules/player/index.js
> +const BASE_URL = 'http://localhost:3000/';
See previous comment about BASE_URL

2018-11-24 23:24 UTC, arieldellano requested changes
Te deje un par de comentarios, dime si tienes alguna duda sobre lo que te puse.

2018-11-25 00:17 UTC, aurre commented on src/store/modules/game/index.js
> +const BASE_URL = 'http://localhost:3000/';
Done!

2018-11-25 00:21 UTC, aurre commented on public/index.html
> +    <link rel="icon" href="<%= BASE_URL %>favicon.png" />
Done!

2018-11-25 00:21 UTC, aurre commented on src/store/modules/player/index.js
> +const BASE_URL = 'http://localhost:3000/';
Done!

2018-11-25 00:59 UTC, Latinneo commented on src/store/modules/game/index.js
> +import BASE_URL from '../../../config/app-settings.js';
puedes usar '@/config/app-settings.js' en lugar de ../../..

2018-11-25 01:00 UTC, Latinneo commented on src/store/modules/player/index.js
> +import BASE_URL from '../../../config/app-settings.js';
usa @/ en lugar de ../../../

2018-11-25 01:00 UTC, aurre commented on src/store/modules/game/index.js
> +import BASE_URL from '../../../config/app-settings.js';
Si, verdad

2018-11-25 01:04 UTC, arieldellano approved these changes

2018-11-25 01:49 UTC, merged